# Generated by Django 3.0.7 on 2020-07-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=120)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('imageSrc', models.ImageField(upload_to='./images/')),
                ('content', models.TextField()),
                ('snippet', models.CharField(default=models.TextField(), max_length=50)),
            ],
        ),
    ]
