# Generated by Django 3.0.7 on 2020-07-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='snippet',
            field=models.TextField(default='<django.db.models.fields.TextField>'),
        ),
    ]
